CREATE OR REPLACE PROCEDURE pastTrainn (v_out_resut OUT TRAINNPACKAGE.tr_cursor)
  IS
  v_sql VARCHAR2(1000):='';
  BEGIN
    v_sql:='SELECT TR_ID, TR_TITLE, TR_CONTENT, TR_BEGIN_TIME, TR_END_TIME, TR_LOCATION, TR_STATUS FROM T_HRSYS_TRAINN WHERE TR_BEGIN_TIME<sysdate';
    OPEN v_out_resut FOR v_sql;
  END;
/

