CREATE OR REPLACE TRIGGER TRIG_ATTE_INSERT_SEQ
  BEFORE INSERT
  ON T_HRSYS_ATTE
  FOR EACH ROW
  DECLARE
  BEGIN
    SELECT HRSYS_ATTE_SEQ.nextval INTO :NEW.ATTE_ID FROM dual;
  END TRIG_ATTE_INSERT_SEQ;
/

