CREATE OR REPLACE TRIGGER TRIG_ATTE_UPDATE_FORBID
  BEFORE UPDATE
  ON T_HRSYS_ATTE
  FOR EACH ROW
  DECLARE
    v_count NUMBER(2);
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    SELECT count(*) INTO v_count FROM T_HRSYS_ATTE WHERE ATTE_EMP_ID=:NEW.ATTE_EMP_ID AND TO_CHAR(ATTE_END_TIME,'yyyy-MM-dd')=TO_CHAR(:NEW.ATTE_END_TIME,'yyyy-MM-dd');
    IF (v_count>0) THEN
      raise_application_error(-20012,'今日已打卡下班');
    END IF;
  END;
/

